"""empty message

Revision ID: 935ec64160c6
Revises: 935ec64160c6
Create Date: 2020-09-25 18:30:30.160505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '935ec64160c6'
down_revision = '935ec64160c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('cliente_doc', table_name='cliente')
    op.drop_column('cliente', 'cliente_doc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('cliente_doc', mysql.DECIMAL(precision=11, scale=0), nullable=False))
    op.create_index('cliente_doc', 'cliente', ['cliente_doc'], unique=True)
    # ### end Alembic commands ###
