"""empty message

Revision ID: fdc87cebb674
Revises: 52fc091aa541
Create Date: 2020-09-25 16:25:11.080741

"""
from alembic import op
import sqlalchemy as sa

import sqlalchemy_utils
# revision identifiers, used by Alembic.
revision = 'fdc87cebb674'
down_revision = '52fc091aa541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_cliente', sa.String(100), nullable=False),
    sa.Column('email_cliente', sa.String(150), nullable=False),
    sa.Column('senha_cliente', sqlalchemy_utils.types.password.PasswordType(256), nullable=False),
    sa.Column('dt_nascimento_cliente', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('email_cliente')
    )
    op.create_table('produto',
    sa.Column('id_produto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_produto', sa.String(150), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id_produto')
    )
    op.create_table('pedido',
    sa.Column('id_pedido', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dt_compra', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_table('produto_pedido',
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id_pedido'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id_produto'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto_pedido')
    op.drop_table('pedido')
    op.drop_table('produto')
    op.drop_table('cliente')
    # ### end Alembic commands ###
